### ISSUE TITLE
Cannot start app

### ISSUE THREAD

**Issue by crsandeep** [marko-js/markojs.com#11]
During start up I saw these 2 errors.

Cannot find module 'highlights'
Cannot find module 'marko-prettyprint'

App started after I added these 2 dependencies. When I try to load http://localhost:8080, I see Error: Error while handling properties for config.plugins: Error while applying option of "plugin". Cause: Error: Plugin module not found for "lasso-cson". Searched from "/Users/sraveesh/git/marko/markoOrig/markojs.com"

I was not able to locate lasso-cson module in npm registry.

**Comment by patrick-steele-idem** [comment]
Hey @crsandeep, I rushed to get the website updated and have not had a chance to publish various packages that are needed. I plan on fixing that early this week. I'll let you know as soon as the markojs.com repo is ready to be used locally by others. Thanks for letting me know. I'll leave this issue open until the problems have been resolved.

**Comment by patrick-steele-idem** [comment]
All dependencies have been published to npm. You should have no problem starting the server with the latest code and after running `npm install`
