### ISSUE TITLE
demo is broken

### ISSUE THREAD

**Issue by seriousme** [marko-js/markojs.com#13]
Hi,

I tried http://markojs.com/try-online/ in chrome 49.0.2623.87m
Which gives me 2 errors:

```
Uncaught Error: Cannot find module "/$/marko-widgets/$/marko" from "/$/marko-widgets/lib"
marko-widgets-77879959.js:23 Uncaught Error: Widget not found: w0
```

Thought you might like to know ;-)

Cheers,
Hans

**Comment by patrick-steele-idem** [comment]
Oh man. Of course, the one time it breaks is when we have an announcement :( It looks like there was a bad build due to caching. It has been fixed now. Thank you for letting us know!
