### ISSUE TITLE
Custom taglib doc link is broken

### ISSUE THREAD

**Issue by jsumners** [marko-js/markojs.com#14]
1. http://markojs.com/docs/marko/language-guide/
2. Click "Custom Tags and Attributes" => http://markojs.com/docs/marko/language-guide/#custom-tags-and-attributes
3. Click "Custom Taglibs" => http://markojs.com/docs/marko/language-guide/#custom-taglibs
4. Nothing happens

**Comment by patrick-steele-idem** [comment]
Thanks for reporting the problem. The correct link should be the following: http://markojs.com/docs/marko/custom-taglibs/

I'll publish a fix.

**Comment by patrick-steele-idem** [comment]
Fixed. Thanks again.
